### ISSUE TITLE
No light entity

### ISSUE THREAD

**Issue by sdaltons1** [gickowtf/pixoo-homeassistant#18]
Hello. Thanks for the integration. I just updated to the latest version. Removed the entry from config.yaml and added with the config flow. 

It now displays the device but the only entity is a "current page" diagnostic sensor. Please let me know if I've done something wrong!

**Comment by gickowtf** [comment]
Would it be possible for you to take a screenshot of the new config?

**Comment by gickowtf** [comment]
Ok, I have the same problem... in any case, the light entity is not displayed directly in the integration. I can only find it via the search.

**Comment by Mrredstone5230** [comment]
When that happened with me I just had to reload the device's page, not really sure why..

**Comment by Mrredstone5230** [comment]
Omg I just found it. It's a merging error when I tried to merge the brightness feature. Fixing it asap. Sorry gicko!

**Comment by gickowtf** [comment]
Fixed in Version 1.4.1

**Comment by gickowtf** [comment]
#19
