### ISSUE TITLE
Unable to add repository

### ISSUE THREAD

**Issue by djgalati** [gickowtf/pixoo-homeassistant#6]
adding this repo to HAOS, I get the following error:

`https://github.com/gickowtf/pixoo-homeassistant is not a valid add-on repository`

Relative noob to this so unsure if this is my fault or an actual issue.

**Comment by gickowtf** [comment]
Hi, I only know HACS and you should be able to install this integration without any problems. I've never heard of HAOS, I hope I'm not on the wrong track.

**Comment by djgalati** [comment]
HAOS is just the home assistant operating system. I have HACS installed, but the error above is present via HACS
