### ISSUE TITLE
page Refresh

### ISSUE THREAD

**Issue by TheVanDoom** [gickowtf/pixoo-homeassistant#75]
Is there a way to trigger a page refresh without switching to the next page? I currently use your integration to display data from my PV power plant. Since it changes quite frequently, I would like to refresh every 5 seconds, but still switch to the next page after i.e. 15 seconds or so. Right now I just duplicated the page :-)

**Comment by Mrredstone5230** [comment]
That is such a good suggestion ! I was thinking of adding a "updateOnEntityUpdate" tag for pages, but I thought it was way too specific. But I think that maybe adding an "update_current_page" service would be quite smart! It could be called by automations built by users that could be more complex then that simple tag. Will try later today..

(Currently, there is no way of doing what you want, but if I add that service, I think it could work quite well!)
