### ISSUE TITLE
Font five_pix doesn't support special character % and °

### ISSUE THREAD

**Issue by Wa77ace** [gickowtf/pixoo-homeassistant#79]
I tried to display the battery percentage on the Divoom display using the font five_pix. The special character "%" couldn't be used. Instead of the "%" an "?" is displayed, which seems to be used, if a special character is not accepted. The same issue occurs, if you try to display temperatures and wanted to use the "°" character. 

If I use the font pico_8, I can display "%", but also not the special character "°".

**Comment by Mrredstone5230** [comment]
Yes, what you are seeing a ? is "normal". The º character isn't implemented in any font, same for the % in five pix. This is a very good idea though!
