### ISSUE TITLE
Frequently goes unavailable

### ISSUE THREAD

**Issue by notmayo** [gickowtf/pixoo-homeassistant#80]
Heyo. I have tried a few things and I ruled out that it is a network/wifi issue. While the pixoo is being ping from home assistant or any other location on my network, it will frequently respond with minimal variance in response time and no dropped packets.

Relevant log files:

- Trying to add from config flow (this eventually works)
`ERROR (MainThread) [custom_components.divoom_pixoo.config_flow] Error setting up Pixoo: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`

- Trying to reload the integration entry
`ERROR (MainThread) [custom_components.divoom_pixoo] Error setting up Pixoo: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`

- General log spam from integration
`ERROR (MainThread) [custom_components.divoom_pixoo] Error setting up Pixoo: HTTPConnectionPool(host='192.168.1.X', port=80): Max retries exceeded with url: /post (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9e03b51e20>, 'Connection to 192.168.1.X timed out. (connect timeout=9)'))`

- Log entry from an automation I made to reload the integration if it become unavailable for 5 minutes
`ERROR (MainThread) [custom_components.divoom_pixoo] Error setting up Pixoo: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`

**Comment by Mrredstone5230** [comment]
Hmm, I've never seen a "connection aborted" error before. From what I can see online, I think it's the pixoo that "denies" the request, for some reason. I currently don't know what I can do to fix this with the integration, but I would sincerely suggest you factory resetting the device, by unplugging the device, holding the power button and at the same time reconnecting the usb cable. It _could_ maybe help...
