### ISSUE TITLE
Service call seems to not work

### ISSUE THREAD

**Issue by ro8inmorgan** [gickowtf/pixoo-homeassistant#81]
I'm not sure if its since the last update with the connection fix, but now when I do a service call HA says succes, but nothing is displayed on the Pixoo. Enabled debug logging and all but I see no errors.

I think it has something to do with the latest Pixoo update.

**Comment by Mrredstone5230** [comment]
Hmm, I'm unfortunately unable to reproduce your issue. For me the service works fine.. Do you mind sharing the service call with it's data that you were trying to send?
