### ISSUE TITLE
Divoo 64 brightness

### ISSUE THREAD

**Issue by stasminaev** [gickowtf/pixoo-homeassistant#83]
Hi guys. Please help me. 
After i start to play with HA integration, the brightness on my Divoo 64 start to be like 50%. 
The Divoo app shows 100%, HA shows 100%, and if I turn the brightness lower, it works. But now when it 100% its not 100% in real life. 
When i reboot the display using reconnect usbc cable - it looks 100% when loading, but when loaded it is like half of the brightness again. 
Can you help me what to do and how to bring back 100% brighness?
Thank you.

**Comment by Mrredstone5230** [comment]
Hmm, strange problem. Could you check in the Divoom app if "night mode" is enabled? Maybe it was left on or something..

I also read something about "high light mode" on the developer API of the pixoo 64, but that option isn't used in this integration. ([http://doc.divoom-gz.com/web/#/12?page_id=342](http://doc.divoom-gz.com/web/#/12?page_id=342)) I'm not sure what it's used for, but maybe it could be the cause of your issue ? (Although again, it's not used in the integration at the moment)

**Comment by stasminaev** [comment]
Sorry Im bad in json requests
I try to test post request from that link but get an erroro "{"error_code": "Request data illegal json"}"
![image](https://github.com/gickowtf/pixoo-homeassistant/assets/68423188/6a786fc7-41df-4f13-9b36-27aa33191e85)
Can you help me with correct request to make sure the reason of my problem is high light mode?

**Comment by Mrredstone5230** [comment]
Hmm, I think your json problem comes from the wrong " symbol. Please use ", since I think your " are different (they look like they're different at the start and at the end of a word). 

I know this is not the same request, but here's one that worked for me on Postman. (I'm not home atm, so I can't really test the light mode request rn)
<img width="872" alt="image" src="https://github.com/gickowtf/pixoo-homeassistant/assets/45701824/e4107726-433d-486f-aa81-b1c6e9bedbfe">

**Comment by stasminaev** [comment]
Thanks a lot! 
Yes, problem was with " "
Now request works fine, but that command didnt help me =(

Still brightness looks like 50% but shows 100%
Here is result of Channel/GetAllConf commmand:

{"error_code": 0, "Brightness":100, "RotationFlag": 0, "ClockTime": 0,"GalleryTime": 0,"SingleGalleyTime": -1,"PowerOnChannelId": 1,"GalleryShowTimeFlag": 0,"CurClockId": 285,"Time24Flag": 1,"TemperatureMode": 0,"GyrateAngle": 0,"MirrorFlag": 0,"LightSwitch": 1}

**Comment by Mrredstone5230** [comment]
Did you try setting it to 0 and 1? Is there a difference between the two?

**Comment by stasminaev** [comment]
Yes, I tried 0 and 1. Nothing happened. There is no difference.

**Comment by Mrredstone5230** [comment]
Hmm. I mean, at this point, I think I would recommend you factory resetting the device by unplugging the device, holding the power button and at the same time reconnecting the usb cable. It could maybe help... At this point, I think the device is very deeply bugged..

**Comment by stasminaev** [comment]
Yes, I will try to do this. Thank you very much for your time!
