### ISSUE TITLE
.620 ERROR (MainThread) [custom_components.divoom_pixoo.sensor] Error rendering page for 192.168.123.146. Is the device connected to the network?

### ISSUE THREAD

**Issue by margag02** [gickowtf/pixoo-homeassistant#87]
The Ip adress is Good, the light sensor is working fine.  Only happen when i try to display a custom_components.

even the sensor divoom_pixoo_64_current_page show the number of the page it supose to display

**Comment by gickowtf** [comment]
Have u try a very simple custom components Site or please Show us your config

**Comment by margag02** [comment]
yes i tried a verry simple components and i have the same result :(

- page_type: components
  duration: 30
  variables:
    time: "{{ now().strftime('%H:%M') }}"
    temp: "{{ states.sensor.salon_avg_temp.state }}"
    rain: >-
      {{ states.sensor.netatmo_martyhome_weather_station_pluviometre_rain.state
      }}
    humidity: |-
      {{
        states.sensor.weather_station_weather_station_weather_station_salon_humidity.state
      }}
    co2: |-
      {{
        states.sensor.weather_station_weather_station_weather_station_salon_co2.state
      }}
    outside: |-
      {{
        states.sensor.netatmo_martyhome_weather_station_module_exterieur_temperature.state
      }}
    presence: "{{ states.binary_sensor.presence_salon_presence.state }}"
  components:
    - type: text
      content: "{{ time }}"
      color: white
      font: PICO_8
      position:
        - 44
        - 1
    - type: image
      image_path: /config/custom_components/divoom_pixoo/img/hum.png
      position:
        - 1
        - 1
    - type: text
      content: "{{ humidity }}%"
      color: >-
        {{ [30,144,255] if humidity|int >= 70 else [255,215,0] if humidity|int
        >= 60 else [50,205,50] if humidity|int >= 30 else [255,215,0] if
        humidity|int >= 25 else [30,144,255]  }}
      font: PICO_8
      position:
        - 17
        - 8
    - type: image
      image_path: /config/custom_components/divoom_pixoo/img/out.png
      position:
        - 1
        - 16
    - type: text
      content: "{{ outside }}"
      color: >-
        {{ [39,0,0] if outside|int >= 39 else [255,0,0] if outside|int >= 32
        else [255,69,0] if outside|int >= 27 else [255,165,0] if outside|int >=
        21 else [210,180,140] if outside|int >= 16 else [124,252,0] if
        outside|int >= 10 else [0,128,0] if outside|int >= 1 else [135,206,235]
        if outside|int <= 0 else [0,0,255] if outside|int <= -6 else [128,0,128]
        if outside|int <= -11 else [186,136,255] if outside|int <= -17 else
        [255,0,255] }}
      font: five_pix
      position:
        - 17
        - 22
    - type: image
      image_path: >-
        {{'/config/custom_components/divoom_pixoo/img/weather/rainy.png' if
        rain|int > 0 else
        '/config/custom_components/divoom_pixoo/img/weather/black.png'}}
      position:
        - 36
        - 20
    - type: image
      image_path: /config/custom_components/divoom_pixoo/img/co2.png
      position:
        - 1
        - 31
    - type: text
      content: "{{ co2 }} ppm"
      color: >-
        {{ [255,175,0] if co2|int >= 2000 else [255,165,0] if co2|int >= 1000
        else [50,205,50]  }}
      font: five_pix
      position:
        - 17
        - 37
    - type: image
      image_path: /config/custom_components/divoom_pixoo/img/in.png
      position:
        - 1
        - 46
    - type: text
      content: "{{ temp }}"
      color: >-
        {{ [255,0,0] if temp|int >= 25 else [50,205,50] if temp|int >= 20 else
        [30,144,255] }}
      font: five_pix
      position:
        - 17
        - 52
- page_type: clock
  duration: 10
  id: 182

**Comment by Mrredstone5230** [comment]
Would you mind re-sharing it with surrounding it with ``` characters please? (for proper formatting)

**Comment by Mrredstone5230** [comment]
So I tried your config and was sort of able to make it work. The only issue I faced was with image components (since I don't have them) Can you please verify that all the paths for your images are correct?

**Comment by margag02** [comment]
yes you are right.....all my image was vanished

Thanks a lot

**Comment by gickowtf** [comment]
@Mrredstone5230  Thank you for Support i will close that issue 🫶
