### ISSUE TITLE
Service for Timer

### ISSUE THREAD

**Issue by laserir** [gickowtf/pixoo-homeassistant#90]
Great piece of work! Are you planning on integration of the timer as a service?

**Comment by gickowtf** [comment]
You mean the standard countdown function from the divoom app, right? A good idea in itself and I'm thinking about it

**Comment by laserir** [comment]
Yes, that’s what I meant. It would only collide with the intended behavior of regular updates in the settings.

**Comment by gickowtf** [comment]
Is it always the same time that the timer should run down or is it always different? Otherwise you could create a timer with the Home Assistant's own Timer Helper and then show it on the display (when it is running) and when it is reached with the pixoo automation, an additional alarm is displayed.

**Comment by laserir** [comment]
That’s the way to go. I’ve used the progress page to display the time remaining of a timer helper. It is only enabled then the state of the timer is active. When the time is up, the buzzer service is called. 👍🏻
