### ISSUE TITLE
Request: Possible to retreive width of text in order to dynamic center text elements? 

### ISSUE THREAD

**Issue by LalaDK** [gickowtf/pixoo-homeassistant#94]
First off - I've really appriciate this integration - thank you.

Is it possible to determine the width of a text with a given font? I'd like to center a text which changes, so right now, it doesn't work nice with a fixed offset.

I can count the amount of characters in the text with filters, but "I" doesn't take as much space as "W", so I don't think that's a good approach. 

Thanks in advance.

**Comment by entrhopi** [comment]
Hi!

This should be fixed with #98 in the new version 1.15.0.
